// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package models

// This document records the list of users
type UsersJson struct {
	// must be int
	Age *int `json:"age,omitempty"`

	// must be string
	Name *string `json:"name,omitempty"`

	// must be string
	Username *string `json:"username,omitempty"`
}
