# docker-compose.yml
version: "3.8"
services:
  web:
    image: nginx
    container_name: nginx-web
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    networks:
      - network-main
  auth:
    image: node:14
    container_name: dummy-auth
    volumes:
      - ../dummy-auth:/mnt
    working_dir: /mnt
    command: npm run dev  
    ports:
      - "5000:5000"
    networks:
      - network-main

networks:
    network-main:
      driver: bridge